#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service single
prepare_service 03-monitoring
PROCESS_NAME="grafana"

sanity_var APP_URL "Full address of application"
bootstrap_directories
configure_monitoring
install_plugins
create_configuration

liftoff
