#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="grafana"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Grafana ${GRAFANA_VERSION}"
sudo -u grafana grafana-server \
                        --homepath="${HOME_PATH}" \
                        --config="${CONFIG_PATH}/${CONFIG_FILE}" \
                        --packaging=docker \
                        "$@" \
                        cfg:default.log.mode="console" \
                        cfg:default.paths.data="$DATA_PATH" \
                        cfg:default.paths.logs="$LOG_PATH" \
                        cfg:default.paths.plugins="$PLUGINS_PATH" \
                        cfg:default.paths.provisioning="$PROVISIONING_PATH"
